" turn off beeps
set noerrorbells
set visualbell

" hide mouse when typing
set mousehide

" search
set ignorecase
set smartcase
set incsearch
set hlsearch
nnoremap <C-H> :noh<CR>

" display line numbers
set number

" visible lines while scrolling
set scrolloff=3

" hide scrollbars
set guioptions-=r
set guioptions-=L

" autosave on focus lost
autocmd BufLeave,FocusLost * silent! wall

" write on buffer change
set autowrite

" read on file change
set autoread

" disable swap and backup
set nobackup
set noswapfile

" colorscheme
" colorscheme anotherdark

" line width
set textwidth=0

" hightlight current line
if has("gui_running")
  set cursorline
endif

" wrapping sucks
set nowrap

" tabs to spaces
set expandtab
set tabstop=2
set shiftwidth=2

" always show status line
if has("gui_running")
  set laststatus=2
endif

" show completion list
set wildmenu

" folding
set foldmethod=syntax
set foldlevel=100

" copy from cursor to line end
nnoremap Y y$

" next tab
map <C-Tab> :tabnext<CR>

" leader to ,
let mapleader = ','

" useful things in insert mode
imap <C-h> <C-o>h
imap <C-j> <C-o>j
imap <C-k> <C-o>k
imap <C-l> <C-o>l
imap <C-d> <C-o>x
imap <C-e> <C-o>$
imap <C-a> <C-o>0

" turn on highlight
syntax on
